### ISSUE TITLE
FATAL: Exposed OPEN_API_KEY

### ISSUE THREAD

**Issue by devsargam** [Ujj1225/MindSnap-ProseMaster#1]
The [.env](https://github.com/Ujj1225/MindSnap-ProseMaster/blob/main/server/.env) file is committed to git and has exposed `open api secret key`

**Comment by devsargam** [comment]
@Ujj1225 I recommend removing `.env` file entirely from git history
Reference: https://stackoverflow.com/questions/43762338/how-to-remove-file-from-git-history

**Comment by Ujj1225** [comment]
Thank you for reminding. I removed it!
